name: CICD for React

on:
  push:
    branches: [main]

jobs:
  run-frontend-on-ec2:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: SSH to instance
        env:
            HOSTNAME: ${{ secrets.SSH_HOST }}
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > my-ssh-key.pem
          chmod 600 my-ssh-key.pem
          ssh -o StrictHostKeyChecking=no -i my-ssh-key.pem ubuntu@${HOSTNAME} '
              cd /home/ubuntu/ &&
              git clone https://github.com/Sahil1384/test-frontend.git &&
              cd /home/ubuntu/test-frontend &&
              npm install &&
              npm run build
              '
