name: CICD for Laravel and React

on:
  push:
    branches:
      - main

jobs:
  run-frontend-on-ec2:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: SSH to instance
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${HOSTNAME} '
              cd /home/ubuntu/ &&
              sudo rm -rf /home/ubuntu/Unnati/Frontend &&
              git clone https://github.com/Sahil1384/test-frontend.git &&
              cd /home/ubuntu/Unnati &&
              git checkout dev-env &&
              cd /home/ubuntu/Unnati/Frontend &&
              npm install &&
              npm run build
              '
